### ISSUE TITLE
Plans to upgrade to 1.2?

### ISSUE THREAD

**Issue by johnlauer** [buckett/ews-java#1]
The EWS Java API is now at rev 1.2. Any thoughts to upgrade this? I want to use Maven to pull this into my project but i'd love it to be version 1.2. This appears to be 1.1.4.

Thanks,
John

**Comment by jkiddo** [comment]
Have a look @ https://github.com/casimirenslip/EWS-Java-API - it is based on 1.2

**Comment by buckett** [comment]
Better of with the MS version: https://github.com/officedev/ews-java-api
