### ISSUE TITLE
Invitation to collaborate on EWS Java API

### ISSUE THREAD

**Issue by vboctor** [buckett/ews-java#2]
Just thought I would let you know that we've released an official repository for the EWS Java API on GitHub:

https://github.com/officedev/ews-java-api

See blog post at:
http://blogs.office.com/2014/08/28/open-sourcing-exchange-web-services-ews-java-api/

The released project already integrates with Maven.

Thanks,
-Victor

**Comment by buckett** [comment]
Thanks, I've added pointers to the Microsoft project.
